# -*- mode: Python -*-

version_settings(constraint='>=0.23.0')

def agent_gateway_install():
    """
    Deploys an Agent Gateway instance into your cluster.
    """

    # Get the directory of this Tiltfile to reference files relative to the extension
    extension_dir = os.path.dirname(__file__)

    k8s_yaml(os.path.join(extension_dir, 'agent-gateway.yaml'))

    k8s_resource(
        'agent-gateway',
        labels=['agent-gateway'],
        resource_deps=['agent-gateway-krakend-operator']
    )
