apiVersion: v1
kind: Namespace
metadata:
  name: ai-gateway
---
apiVersion: agentic-layer.ai/v1alpha1
kind: AiGateway
metadata:
  labels:
  name: ai-gateway
  namespace: ai-gateway
spec:
  aiGatewayClassName: litellm
  aiModels:
    - name: gemini-2.5-flash-lite
      provider: gemini
