global:
  testWorkflows:
    createOfficialTemplates: false
cronJobs:
  enabled: true

mongodb:
  enabled: false

postgresql:
  enabled: true

testkube-api:
  mongodb:
    enabled: false
  postgresql:
    enabled: true