# -*- mode: Python -*-

version_settings(constraint='>=0.23.0')


def cert_manager_install(version="v1.20.2"):
    """
    Installs cert-manager into your cluster using the official Helm chart.
    """

    k8s_custom_deploy(
        'cert-manager',
        deps=[],
        apply_cmd="""
set -ex
helm upgrade -i cert-manager \\
    oci://quay.io/jetstack/charts/cert-manager \\
    --version {version} \\
    --namespace cert-manager \\
    --create-namespace \\
    --set crds.enabled=true \\
    --set securityContext.runAsUser=1000 \\
    --set webhook.securityContext.runAsUser=1000 \\
    --set cainjector.securityContext.runAsUser=1000 \\
    --set startupapicheck.securityContext.runAsUser=1000 \\
    --wait 1>&2
kubectl wait validatingwebhookconfiguration/cert-manager-webhook \\
    --for "jsonpath={{.webhooks[0].clientConfig.caBundle}}" \\
    --timeout 5m 1>&2
kubectl get -n cert-manager deployment -l app.kubernetes.io/instance=cert-manager -o yaml
""".format(version=version),
        delete_cmd="""
helm uninstall cert-manager --namespace cert-manager 2>/dev/null || true
""",
    )

    k8s_resource(
        'cert-manager',
        resource_deps=[],
    )
